# --- General options --- #

# Name of website
title: hyperparameters.ml

# Short description of your site
description: A virtual proof that I'm awesome

# --- Local development options ---
# If your website is hosted locally rather than on GitHub, then you need to uncomment the next two parameters to set the url and baseurl
# *** If you're not sure what this mean, then leave this section as it is. Only modify the url and baseurl if you know what you're doing!***

# url is the the website domain URL without a trailing slash
#url: "https://example.com"

# baseurl should be an empty string
#baseurl: ""

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  About Me: "aboutme"
  Resources:
    - Quizlet : "https://hyperparameters.ml/2019-07-12-quizlet/"
  Cv's : "fort"
  Tag index : "tags"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon.jpeg"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: /path/to/image

# --- Background colour/image options --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

# navbar-img: "/img/bgimage.png"
# footer-img: "/img/bgimage.png"
# page-img: "/img/bgimage.png"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Karina Suarez

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
  rss: false
  email: "kcrycss@example.com"
  facebook: NZT480
  github: the-shy-beattle
  twitter: zzzrayos
#  reddit: yourname
#  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: the_shy_beetle
#  youtube: user/deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  intagram: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "hyperparameters.ml"  # eg. "deanattali.com/beautiful-jekyll"

# --- Web about me Section --- #


# --- Web Statistics Section --- #
fort:
  work_paragraph: 'Currently I am working as <strong>Web Engineer</strong> at
                  <a href="https://home.cern.ch">CERN</a> (Switzerland).
                   Previously I worked as a <strong>freelance web developer</strong>, building
                    amazing projects for several companies and also
                    on a startup (<a href="http://adamaweb.com">Adama Web</a>).'
  aboutme_paragraph: 'My name is <span itemprop="name">René Fernández</span> and
                      I am a <span itemprop="jobtitle">Web Engineer</span>.
                      In this site you can find some information about my
                      professional and personal activity.'
  studies_paragraph: 'Obtained my <strong>Masters Degree on Web Engineering</strong>
                      and my <strong>Bachelor in Computer Science</strong> from
                      the University of Oviedo. My Masters
                      thesis was "<a href="https://goo.gl/bcvkrw"
                      title="Codesnug: Code storage social tool">
                      Codesnug: Code storage social tool</a>",
                      obtaining the grade of "Excelent".'
  code_paragraph: 'I enjoy coding and managing the lyfecycle of projects, materializing my ideas on
                  fully-working applications. <strong>I love to build useful and cool stuff!</strong>'
  free_time_paragraph: 'I like to go hiking, taking pictures, weekend travels,
                        playing video games and also writing on my blog.'
  projects_paragraph: 'You can checkout some of my previous projects on the
                      projects page (Actually only those I am prouder of :))'
  more_info_paragraph: 'Grew up in Asturias, Spain, I have been always a <strong>technology enthusiastic</strong> so
                        I decided to study computer science. After finishing my
                        studies I moved to Geneva, Switzerland, to continue my career
                        on the IT field.'
  contact:
      title: Contact
      first_paragraph: 'If you want to contact me you can <a href="mailto:hola@renefernandez.com?subject=Hello
                        from renefernandez.com">email me</a> or find me
                        <a href="https://twitter.com/zzzrayos">on Twittermessage, I am always open to new and exciting opportunities!'
      form_paragraph: 'You can also send me a qui</a>.
                        Do not hesitate to send a ck message using the form below'
      email_field: 'Email'
      name_field: 'Name'
      message_field: 'Message'
      submit_button: 'Submit'
# Fill in your Google Analytics gtag.js ID to track your website using gtag
#gtag: ""

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.

#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Comments --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
# disqus: ""

# If you want to use JustComments fill with the API Key
#just-comments: "ABCD-EFGH-IJKL"

# To use Facebook Comments, fill in a Facebook App ID
# fb_comment_id: ""

# To use Staticman comments, fill in repository, branch, and endpoint
staticman:
  repository : # GitHub username/repository eg. "daattali/beautiful-jekyll"
  branch     : master # If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
  endpoint   : # URL of your own deployment, with a trailing slash (will fallback to a public GitLab instance) eg. https://<your-api>/v3/entry/github/
  reCaptcha:
    # reCaptcha for Staticman (OPTIONAL, but recommended for spam protection)
    # If you use reCaptcha, you must also set these parameters in staticman.yml
    siteKey  : # Use your own site key, you need to apply for one on Google
    secret   : # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret>

# --- Misc --- #

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
